# Generated by Django 3.2.7 on 2021-09-25 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasi', '0009_auto_20210923_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datum_isteka_oglasa',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 16, 54, 13, 419212)),
        ),
    ]
