# Generated by Django 3.2.7 on 2021-09-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankete', '0002_auto_20210925_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stavka',
            name='tekst',
        ),
        migrations.AlterField(
            model_name='pitanja',
            name='pitanje',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stavka',
            name='pitanje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ankete.pitanja'),
        ),
    ]
